# Generated by Django 4.2.4 on 2024-01-01 04:26

import core.utils.models_helpers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0009_alter_attempthaslocationchallenge_attempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeattempt",
            name="incrementation_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="challengeattempt",
            name="number_of_attempts",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Number of attempts cannot be negative."
                    ),
                    django.core.validators.MaxValueValidator(
                        1,
                        message="Number of attempts cannot exceed the maximum allowed.",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="challengeattempt",
            name="profile_of_attempt",
            field=core.utils.models_helpers.SlugFieldForeignKey(
                blank=True,
                max_length=500,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="slug",
            ),
        ),
        migrations.AlterField(
            model_name="staychallenge",
            name="max_number_of_attempts",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="staychallenge",
            name="winner_slug",
            field=models.SlugField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="ProfileRemainingAttempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_attempts", models.IntegerField(default=5)),
                (
                    "challenge_id",
                    core.utils.models_helpers.NullableBigIntegerForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.staychallenge",
                    ),
                ),
                (
                    "profile_slug",
                    core.utils.models_helpers.SlugFieldForeignKey(
                        blank=True,
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="slug",
                    ),
                ),
            ],
        ),
    ]
